---
title: "Research"
description: I lead interdisciplinary research that explores relationships between technological change and factors that shape it, such as consumer behavior, market dynamics, and policy. I apply a systems engineering perspective to better understand these relationships and to inform policy, with an emphasis on accelerating transitions to cleaner technologies. I have expertise in choice modeling, survey design, programming in R, China, and the global electric vehicle industry.
preview: images/lab/john_helveston.png
execute: 
  echo: false
  message: false
  warning: false
format: html 
toc: true
toc-location: left
---

<!-- Remove margin under list items -->

<style>
ol {
    margin-bottom: 5px;
}
p {
  margin: 5px 0 0 0;
}
</style>

```{r setup}
source("_common.R")

# Update local copy of "pubs" Google sheet
# write_csv(get_pubs(), here::here('content', 'pubs.csv'))

# Get local copy of pubs
# pubs <- read_csv(here::here('content', 'pubs.csv'))

# Get pubs from Google sheet
pubs <- get_pubs()
```

<center>

[View my full CV here](cv.qmd)

`r htmltools::HTML(paste0(icon_link(icon = "ai ai-google-scholar", text = "Google Scholar", url  = "https://scholar.google.com/citations?user=DY2D56IAAAAJ"), icon_link(icon = "ai ai-orcid", text = "ORCID", url  = "https://orcid.org/0000-0002-2657-9191"), icon_link(icon = "ai ai-researchgate", text = "Research Gate", url = "https://www.researchgate.net/profile/John_Helveston")))`

<br>

<u>Underline</u> indicates advisee; * graduate student, **undergraduate student

</center>

<br>

## Refereed (Peer-Reviewed) Journal Articles

`r make_pub_list(pubs, "peer_reviewed")`

## Refereed Articles in Conference Proceedings

`r make_pub_list(pubs, "conference")`

## Working Papers & Papers Under Review

`r make_pub_list(pubs, "working")`

## Magazine Publications

`r make_pub_list(pubs, "magazine")`

## Books and Book Chapters

`r make_pub_list(pubs, "book")`

## Opinion Editorials

`r make_pub_list(pubs, "oped")`

## Podcasts

`r make_pub_list(pubs, "podcast")`

## Other

`r make_pub_list(pubs, "other")`

## Theses

`r make_pub_list(pubs, "theses")`

## Student Theses

<aside>Theses by students advised by Helveston</aside>

`r make_pub_list(pubs, "theses_student")`

## Software

`r make_pub_list(pubs, "software")`

## Media Coverage

`r make_media_list()`
